# Generated by Django 4.1.7 on 2023-07-11 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ic01', models.CharField(db_column='IC01', max_length=8)),
                ('account_name', models.CharField(db_column='Account_Name', max_length=100)),
                ('benchmark_date', models.DateTimeField(db_column='Benchmark_Date')),
                ('profit', models.FloatField(db_column='Profit')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='Created_At')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='Updated_At')),
            ],
        ),
        migrations.CreateModel(
            name='AccountData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('financial_impact', models.IntegerField(db_column='Financial_Imapct')),
                ('year', models.IntegerField(db_column='Year')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='Created_At')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='Updated_At')),
                ('account_ID', models.ForeignKey(db_column='Account_ID', on_delete=django.db.models.deletion.CASCADE, to='base.account')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ftid', models.CharField(db_column='Ftid', max_length=8)),
                ('username', models.CharField(db_column='Username', max_length=100)),
                ('age', models.IntegerField(db_column='Age')),
                ('email', models.EmailField(db_column='Email', max_length=254)),
                ('disclaimer', models.BooleanField(db_column='Disclaimer')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='Created_At')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='Updated_At')),
            ],
        ),
        migrations.CreateModel(
            name='UsersAccounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='Created_At')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='Updated_At')),
                ('account_ID', models.ForeignKey(db_column='Account_ID', on_delete=django.db.models.deletion.CASCADE, to='base.account')),
                ('user_ID', models.ForeignKey(db_column='User_ID', on_delete=django.db.models.deletion.CASCADE, to='base.user')),
            ],
        ),
        migrations.DeleteModel(
            name='Userdb',
        ),
        migrations.AddField(
            model_name='accountdata',
            name='updated_by_user_ID',
            field=models.ForeignKey(db_column='Updated_By', on_delete=django.db.models.deletion.CASCADE, related_name='updated_by', to='base.user'),
        ),
        migrations.AddField(
            model_name='accountdata',
            name='user_ID',
            field=models.ForeignKey(db_column='User_ID', on_delete=django.db.models.deletion.CASCADE, related_name='User_ID', to='base.user'),
        ),
    ]
