# Generated by Django 4.1.7 on 2023-07-11 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_account_accountdata_user_usersaccounts_delete_userdb_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_column='Updated_At', null=True),
        ),
        migrations.AlterField(
            model_name='accountdata',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_column='Updated_At', null=True),
        ),
        migrations.AlterField(
            model_name='accountdata',
            name='user_ID',
            field=models.ForeignKey(db_column='User_ID', on_delete=django.db.models.deletion.CASCADE, related_name='user_ID', to='base.user'),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_column='Updated_At', null=True),
        ),
        migrations.AlterField(
            model_name='usersaccounts',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_column='Updated_At', null=True),
        ),
    ]
