# Generated by Django 4.1.7 on 2023-07-11 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_account_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountdata',
            name='updated_by_user_ID',
            field=models.ForeignKey(db_column='Updated_By', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_by', to='base.user'),
        ),
    ]
