# Generated by Django 4.1.7 on 2023-07-12 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_accountdata_updated_by_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountdata',
            old_name='account_ID',
            new_name='account_id',
        ),
        migrations.RenameField(
            model_name='accountdata',
            old_name='updated_by_user_ID',
            new_name='updated_by_user_id',
        ),
        migrations.RenameField(
            model_name='usersaccounts',
            old_name='account_ID',
            new_name='account_id',
        ),
        migrations.RenameField(
            model_name='usersaccounts',
            old_name='user_ID',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='accountdata',
            old_name='user_ID',
            new_name='user_id',
        ),
        migrations.AlterField(
            model_name='account',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_column='Updated_At'),
        ),
        migrations.AlterField(
            model_name='accountdata',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_column='Updated_At'),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_column='Updated_At'),
        ),
        migrations.AlterField(
            model_name='usersaccounts',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_column='Updated_At'),
        ),
    ]
