# Generated by Django 4.1.7 on 2023-07-12 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_rename_account_id_accountdata_account_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountdata',
            name='user_id',
            field=models.ForeignKey(db_column='User_ID', on_delete=django.db.models.deletion.CASCADE, related_name='user_id', to='base.user'),
        ),
    ]
