# Generated by Django 4.1.7 on 2023-07-12 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_delete_accountdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('financial_impact', models.IntegerField(db_column='Financial_Imapct')),
                ('year', models.IntegerField(db_column='Year')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='Created_At')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='Updated_At')),
                ('account_id', models.ForeignKey(db_column='Account_ID', on_delete=django.db.models.deletion.CASCADE, to='base.account')),
                ('updated_by_user_id', models.ForeignKey(db_column='Updated_By', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_by', to='base.user')),
                ('user_id', models.ForeignKey(db_column='User_ID', on_delete=django.db.models.deletion.CASCADE, related_name='user_id', to='base.user')),
            ],
        ),
    ]
