# Generated by Django 4.1.7 on 2023-07-14 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_accountdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.IntegerField(db_column='Age', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='disclaimer',
            field=models.BooleanField(db_column='Disclaimer', null=True),
        ),
    ]
